packages:
  - playground
  - docs

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - unrs-resolver
  - vue-demi

overrides:
  '@movk/core': https://pkg.pr.new/@movk/core@70

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
