packages:
  - playgrounds/*
  - docs

allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false

overrides:
  '@nuxt/content': ^3.14.0
  '@movk/core': https://pkg.pr.new/@movk/core@e58648f
