import type { z } from 'zod'
import type { IsComponent } from '@movk/core'
import type { AutoFormControl, AutoFormControls, AutoFormField, AutoFormMergeMeta } from '../../types/auto-form'
import { markRaw } from 'vue'
import { z as zod } from 'zod'
import { joinPath, startCase, toPath, isFunction, isObject } from '@movk/core'
import { getAutoFormMetadata } from './metadata'
import { AUTOFORM_LIMITS, AUTOFORM_META } from '../../constants/auto-form'
import type { ZodAutoFormFieldMeta } from '../../types/zod'

/** 获取 schema 的内层类型（optional/default/pipe 等包装的内部 schema） */
function getUnwrappedSchema(schema: any): z.ZodType | undefined {
  const def = schema?.def || schema?._def
  return def?.innerType || def?.in || def?.schema || undefined
}

/** 剥离 optional/readonly/default 等装饰层，返回装饰信息和核心 schema */
function extractDecorators(schema: z.ZodType): {
  decorators: AutoFormField['decorators']
  coreSchema: z.ZodType
} {
  const decorators: AutoFormField['decorators'] = {}
  let cur: any = schema
  let coreSchema: z.ZodType = schema

  while (cur) {
    const def = cur?.def || cur?._def
    if (!def?.type)
      break
    switch (def.type) {
      case 'optional':
        decorators.isOptional = true
        break
      case 'readonly':
        decorators.isReadonly = true
        break
      case 'default':
        decorators.defaultValue = isFunction(def.defaultValue)
          ? def.defaultValue()
          : def.defaultValue
        break
    }

    const next = getUnwrappedSchema(cur)
    if (!next)
      break

    if (next === cur)
      break

    cur = next
    coreSchema = next
  }

  /**
   * @deprecated z.describe() 已废弃，建议使用 z.meta({ description: '...' }) 代替
   * @see https://zod.dev/metadata?id=describe
   */
  if (coreSchema.description) {
    decorators.description = coreSchema.description
  }

  return { decorators, coreSchema }
}

/** 合并全局 meta、字段自定义 meta 与装饰器信息，确定最终渲染类型 */
function extractSchemaInfo(schema: z.ZodType, globalMeta: ZodAutoFormFieldMeta, autoGeneratedLabel: string) {
  const customMeta = getAutoFormMetadata(schema)
  const { decorators, coreSchema } = extractDecorators(schema)
  const computedType = customMeta?.component ? undefined : (customMeta?.type ?? (coreSchema as any)?.type)

  const mergedMeta = {
    ...{
      required: !decorators.isOptional,
      description: decorators.description,
      label: autoGeneratedLabel
    } as AutoFormField['meta'],
    ...globalMeta,
    ...customMeta,
    type: computedType,
    ...(customMeta?.overwrite && isObject(customMeta.overwrite) ? customMeta.overwrite : {})
  } as AutoFormMergeMeta

  return { decorators, mergedMeta, coreSchema }
}

/** 根据 meta.component 或 type 映射找到对应的渲染控件 */
function selectComponent(
  mergedMeta: AutoFormMergeMeta,
  finalType: string | undefined,
  mapping: AutoFormControls
): { chosenComponent: IsComponent | undefined, mapped: AutoFormControl<IsComponent> | undefined } {
  let chosenComponent: IsComponent | undefined
  let mapped: AutoFormControl<IsComponent> | undefined

  if (mergedMeta.component) {
    chosenComponent = mergedMeta.component
  } else if (finalType && finalType in mapping) {
    mapped = mapping[finalType as keyof typeof mapping]
    chosenComponent = mapped?.component
  }

  if (chosenComponent && typeof chosenComponent !== 'string') {
    chosenComponent = markRaw(chosenComponent)
  }

  return { chosenComponent, mapped }
}

function createField(
  path: string,
  coreSchema: z.ZodType,
  decorators: AutoFormField['decorators'],
  mergedMeta: AutoFormMergeMeta
): AutoFormField {
  return {
    path,
    schema: coreSchema,
    decorators,
    meta: mergedMeta
  }
}

/** 从枚举 schema 中提取所有可选值 */
function extractEnumValues(schema: z.ZodType): Array<string | number> | undefined {
  if ((schema as any).enum && typeof (schema as any).enum === 'object') {
    return Object.values((schema as any).enum)
  }

  const def = (schema as any)._def
  if (def?.values) {
    return Array.isArray(def.values) ? def.values : Array.from(def.values)
  }

  return undefined
}

/** 处理数组类型字段，递归解析元素 schema 并挂载到 field.arrayElement */
function handleArrayField(params: {
  schema: z.ZodType
  path: string
  decorators: AutoFormField['decorators']
  meta: AutoFormMergeMeta
  mapping: AutoFormControls
  globalMeta: ZodAutoFormFieldMeta
}): AutoFormField[] {
  const { schema, path, decorators, meta, mapping, globalMeta } = params
  const elementSchema = (schema as any).unwrap?.()

  if (!elementSchema) {
    return []
  }

  const field = createField(path, schema, decorators, { ...meta, type: 'array' })

  const [arrayElement] = introspectSchema(elementSchema, mapping, path, globalMeta)

  if (arrayElement) {
    field.arrayElement = arrayElement
  }

  return [field]
}

/** 处理对象类型字段：根路径时扁平化展开，否则生成带 children 的嵌套字段 */
function handleObjectField(params: {
  schema: z.ZodType
  path: string
  decorators: AutoFormField['decorators']
  meta: AutoFormMergeMeta
  mapping: AutoFormControls
  globalMeta: ZodAutoFormFieldMeta
}): AutoFormField[] {
  const { schema, path, decorators, meta, mapping, globalMeta } = params
  const shape = (schema as any).shape

  if (!shape || typeof shape !== 'object') {
    return []
  }

  const shapeKeys = Object.keys(shape)

  if (shapeKeys.length > AUTOFORM_LIMITS.MAX_OBJECT_PROPERTIES) {
    return []
  }

  if (!path) {
    return shapeKeys.flatMap(key =>
      introspectSchema(shape[key] as z.ZodType, mapping, key, globalMeta)
    )
  }

  const field = createField(path, schema, decorators, meta)
  field.children = shapeKeys.flatMap((key) => {
    const childPath = joinPath([...toPath(path), key])
    return introspectSchema(shape[key] as z.ZodType, mapping, childPath, globalMeta)
  })

  return [field]
}

/** 处理布局字段，将 meta.layout.fields 解析为子字段并挂载到 children */
function handleLayoutField(params: {
  schema: z.ZodType
  path: string
  meta: AutoFormMergeMeta
  mapping: AutoFormControls
  globalMeta?: ZodAutoFormFieldMeta
}): AutoFormField[] {
  const { schema, path, meta, mapping, globalMeta = {} } = params
  const shape = meta?.layout?.fields as Record<string, z.ZodType> | undefined

  if (!shape || typeof shape !== 'object') {
    return []
  }

  const pathSegments = toPath(path)
  const actualParentPath = pathSegments.slice(0, -1).join('.')
  const layoutField = createField(path, schema, {}, meta)

  layoutField.children = Object.keys(shape).flatMap((key) => {
    const childSchema = shape[key]
    if (!childSchema) return []

    const childPath = actualParentPath ? `${actualParentPath}.${key}` : key
    return introspectSchema(childSchema, mapping, childPath, globalMeta)
  })

  return [layoutField]
}

/** 将 Zod schema 递归解析为 AutoFormField 列表（schema 遍历的核心入口） */
export function introspectSchema(
  schema: z.ZodType,
  mapping: AutoFormControls,
  path: string,
  globalMeta: ZodAutoFormFieldMeta = {}
): AutoFormField[] {
  const fieldName = path.split('.').pop()
  const autoGeneratedLabel = fieldName ? startCase(fieldName) : ''
  const { decorators, mergedMeta, coreSchema } = extractSchemaInfo(schema, globalMeta, autoGeneratedLabel)

  if (!coreSchema) {
    return []
  }

  const fieldType = mergedMeta.type

  if (fieldType === AUTOFORM_META.LAYOUT_KEY) {
    return handleLayoutField({ schema: coreSchema, path, meta: mergedMeta, mapping, globalMeta })
  }

  if (fieldType === 'array' || (coreSchema.type === 'array' && !mergedMeta.overwrite)) {
    return handleArrayField({ schema: coreSchema, path, decorators, meta: mergedMeta, mapping, globalMeta })
  }

  if (fieldType === 'object') {
    return handleObjectField({ schema: coreSchema, path, decorators, meta: mergedMeta, mapping, globalMeta })
  }

  const field = createField(path, coreSchema, decorators, mergedMeta)
  const { chosenComponent, mapped } = selectComponent(mergedMeta, fieldType, mapping)

  field.meta.component = chosenComponent
  field.meta.mapped = mapped

  if (coreSchema.type === 'enum' && mapped) {
    const enumValues = extractEnumValues(coreSchema)
    if (enumValues && enumValues.length > 0) {
      field.meta.controlProps = {
        items: enumValues,
        ...(field.meta.controlProps as unknown as Record<string, unknown>)
      } as unknown as AutoFormMergeMeta['controlProps']
    }
  }

  return [field]
}

/** 判断 schema 是否为布局占位标记（type === '__layout__'） */
function isLayoutMarker(schema: z.ZodType): boolean {
  const meta = getAutoFormMetadata(schema)
  return meta?.type === AUTOFORM_META.LAYOUT_KEY
}

/** 将 shape 中的布局标记字段展开为其 layout.fields 内的普通字段（递归） */
function processLayoutShape(shape: Record<string, z.ZodType>): Record<string, z.ZodType> {
  const resultShape: Record<string, z.ZodType> = {}

  for (const [key, fieldSchema] of Object.entries(shape)) {
    if (isLayoutMarker(fieldSchema)) {
      const meta = getAutoFormMetadata(fieldSchema)
      const layoutFields = meta?.layout?.fields

      if (layoutFields && isObject(layoutFields)) {
        Object.assign(resultShape, processLayoutShape(layoutFields))
      }
    } else {
      resultShape[key] = fieldSchema
    }
  }

  return resultShape
}

/** 将含布局标记的 schema 还原为纯字段 schema，用于 Zod 表单校验 */
export function extractPureSchema<T extends z.ZodObject<any, any>>(schema: T): z.ZodObject<any, any> {
  const shape = (schema as any).shape

  if (!shape || typeof shape !== 'object') {
    return schema
  }

  const hasLayoutMarker = Object.values(shape).some(fieldSchema =>
    isLayoutMarker(fieldSchema as z.ZodType)
  )

  if (!hasLayoutMarker) {
    return schema
  }

  const pureShape = processLayoutShape(shape)

  return zod.object(pureShape) as z.ZodObject<any, any>
}
