import type { AnyObject } from '@movk/core'
import type { GlobalMeta, z } from 'zod/v4'
import type { IsComponent, ReactiveValue } from '../core'
import type { AutoFormControl, AutoFormControls, AutoFormControlsMeta, AutoFormField, AutoFormFieldContext } from '../types/auto-form'
import { isFunction, isObject } from '@movk/core'
import { Fragment, h, isRef, isVNode, markRaw, unref } from 'vue'
import { joinPath, startCase, toPath } from '../core'

/**
 * 按“外层 → 内层”依次遍历 zod 装饰器链
 */
function* iterateZodChain(root: z.ZodType): Generator<any> {
  let cur: any = root
  while (cur) {
    yield cur
    cur = cur?.def?.innerType
  }
}

/**
 * 提取 schema 信息
 */
function extractSchemaInfo(schema: z.ZodType) {
  const decorators = {
    isOptional: false,
    defaultValue: undefined as any,
    description: undefined as string | undefined,
  }

  let mergedMeta: GlobalMeta & AutoFormControlsMeta = {}
  let coreSchema: z.ZodType = schema

  for (const node of iterateZodChain(schema)) {
    // 收集 meta
    if (node?.meta && isFunction(node.meta)) {
      mergedMeta = { ...node.meta(), ...mergedMeta }
    }

    // 收集装饰器信息
    const defType = node?.def?.type
    if (defType === 'optional')
      decorators.isOptional = true
    if (defType === 'default') {
      decorators.defaultValue = isFunction(node.def.defaultValue)
        ? node.def.defaultValue()
        : node.def.defaultValue
    }
    if (node?.description)
      decorators.description = node.description

    coreSchema = node
  }

  return { coreSchema, decorators, mergedMeta }
}

/**
 * 递归地分析 Zod schema，返回一个包含所有字段信息的数组
 */
export function introspectSchema(
  schema: z.ZodType,
  mapping: AutoFormControls,
  parentPath?: string,
): AutoFormField[] {
  const result: AutoFormField[] = []
  const { coreSchema, decorators, mergedMeta } = extractSchemaInfo(schema)
  const type = (coreSchema as any).type

  // 通用字段信息提取
  const fieldName = parentPath ? parentPath.split('.').pop() || '' : ''
  const autoGeneratedLabel = fieldName ? startCase(fieldName) : ''
  const finalDescription = mergedMeta.description ?? decorators.description
  const finalLabel = mergedMeta.label ?? autoGeneratedLabel
  const finalRequired = mergedMeta.required || !decorators.isOptional

  if (type === 'object') {
    const shape = (coreSchema as any).shape
    // 如果是根级别（parentPath 为空），直接处理子字段，不创建容器
    if (!parentPath) {
      for (const key of Object.keys(shape)) {
        const child = shape[key] as z.ZodType
        result.push(...introspectSchema(child, mapping, key))
      }
      return result
    }

    const accordionItem = {
      path: parentPath ?? '',
      schema: coreSchema,
      originalSchema: schema,
      decorators,
      meta: {
        ...mergedMeta,
        label: finalLabel,
        description: finalDescription,
        required: finalRequired,
      },
      children: [],
    } as AutoFormField

    // 递归处理子字段
    for (const key of Object.keys(shape)) {
      const child = shape[key] as z.ZodType
      const childPath = joinPath([...toPath(parentPath), key])
      accordionItem.children!.push(...introspectSchema(child, mapping, childPath))
    }

    result.push(accordionItem)
    return result
  }

  const finalType = mergedMeta.component ? undefined : (mergedMeta.type ?? type)

  let chosenComponent: IsComponent | undefined
  let mapped: AutoFormControl<IsComponent> | undefined

  if (mergedMeta.component) {
    chosenComponent = mergedMeta.component
  }
  else if (finalType) {
    mapped = mapping[finalType as keyof typeof mapping]
    chosenComponent = mapped?.component
  }

  if (chosenComponent && typeof chosenComponent !== 'string') {
    chosenComponent = markRaw(chosenComponent)
  }

  result.push({
    path: parentPath ?? '',
    schema: coreSchema,
    originalSchema: schema,
    decorators,
    meta: {
      ...mergedMeta,
      type: finalType,
      label: finalLabel,
      description: finalDescription,
      required: finalRequired,
      component: chosenComponent,
      mapped,
    },
  })
  return result
}

function normalize(node: any): any[] {
  if (node == null || node === false)
    return []

  if (Array.isArray(node))
    return node.flatMap(n => normalize(n))

  if (isVNode(node))
    return [node]

  const t = typeof node
  if (t === 'string' || t === 'number')
    return [node]

  // 其它对象不参与字符串化，避免触发 JSON.stringify 循环
  return []
}

export function VNodeRender(props: { node: unknown }) {
  const children = normalize(props.node as any)
  if (children.length === 0)
    return null as any
  if (children.length === 1)
    return children[0] as any
  return h(Fragment, null, children)
}

export function resolveReactiveValue(value: ReactiveValue<any, any>, context: AutoFormFieldContext): any {
  if (isFunction(value)) {
    return (value as (ctx: AutoFormFieldContext) => any)(context)
  }
  return unref(value)
}

export function resolveReactiveObject<T extends Record<string, any>>(
  obj: T,
  context: AutoFormFieldContext,
): T {
  // 处理数组
  if (Array.isArray(obj)) {
    return obj.map((item) => {
      if (isObject(item) && item !== null && !isRef(item) && !isVNode(item)) {
        return resolveReactiveObject(item, context)
      }
      return resolveReactiveValue(item, context)
    }) as unknown as T
  }

  // 处理对象
  const result = {} as T
  for (const [key, value] of Object.entries(obj)) {
    if (isObject(value) && value !== null && !isRef(value) && !isVNode(value)) {
      (result as any)[key] = resolveReactiveObject(value, context)
    }
    else {
      (result as any)[key] = resolveReactiveValue(value, context)
    }
  }
  return result
}

// 增强事件属性函数 - 为Vue组件的事件处理函数注入表单字段上下文
export function enhanceEventProps(originalProps: AnyObject, ctx: AutoFormFieldContext) {
  const next: Record<string, any> = {}
  for (const key of Object.keys(originalProps || {})) {
    const val = (originalProps as any)[key]
    if (/^on[A-Z].+/.test(key) && isFunction(val)) {
      next[key] = (...args: any[]) => (val as any)(...args, ctx)
    }
    else {
      next[key] = val
    }
  }
  return next
}
